<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="INCNU4129FFM" failures="1" tests="3" name="Test" time="26.476" errors="0" timestamp="2020-08-07T18:01:21 IST">
  <testcase classname="listnwers.Demo" name="listeners2" time="24.698">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at listnwers.Demo.listeners2(Demo.java:64)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- listeners2 -->
  <testcase classname="listnwers.Demo" name="listeners3" time="24.819">
    <skipped/>
  </testcase> <!-- listeners3 -->
  <testcase classname="listnwers.Demo" name="listeners1" time="26.205"/>
</testsuite> <!-- Test -->
